// Code generated by script/gen-palette.sh. DO NOT EDIT.
//
// Source: nebelung palette/*.hex.json at rev eecee94.
// Regenerate with: script/gen-palette.sh ~/code/workshop/nebelung

package snug

// palette holds the hex value of every nebelung token a role resolves to,
// for each of the four variants. Roles are named in theme.go; this file is
// only ever the numbers.
var palette = map[Variant]map[string]string{
	Nebelung: { // dark  · the default
		"mauve":    "#c9a8f1",
		"green":    "#abe1a6",
		"peach":    "#f5b58e",
		"red":      "#ed8fa9",
		"overlay1": "#858585",
		"sapphire": "#7dc6e7",
		"teal":     "#9be0d5",
		"subtext0": "#aeaeae",
	},
	NebelungHighContrast: { // dark  · 19.9:1 text on base
		"mauve":    "#c9a8f1",
		"green":    "#abe1a6",
		"peach":    "#f5b58e",
		"red":      "#ed8fa9",
		"overlay1": "#8e8e8e",
		"sapphire": "#7dc6e7",
		"teal":     "#9be0d5",
		"subtext0": "#c6c6c6",
	},
	NebelungLatte: { // light
		"mauve":    "#8545e3",
		"green":    "#4a9e3a",
		"peach":    "#f66d2d",
		"red":      "#ca2a40",
		"overlay1": "#909090",
		"sapphire": "#379eb1",
		"teal":     "#2f9197",
		"subtext0": "#717171",
	},
	NebelungLatteHC: { // light · 9.9:1
		"mauve":    "#8545e3",
		"green":    "#4a9e3a",
		"peach":    "#f66d2d",
		"red":      "#ca2a40",
		"overlay1": "#8d8d8d",
		"sapphire": "#379eb1",
		"teal":     "#2f9197",
		"subtext0": "#686868",
	},
}
