"""Render palette.go from nebelung's four variant hex files. See gen-palette.sh."""
import json, subprocess, sys, os

NEB = sys.argv[1]
VARIANTS = [
    ("Nebelung",            "nebelung",                     "dark  · the default"),
    ("NebelungHighContrast","nebelung-high-contrast",        "dark  · 19.9:1 text on base"),
    ("NebelungLatte",       "nebelung-latte",                "light"),
    ("NebelungLatteHC",     "nebelung-latte-high-contrast",  "light · 9.9:1"),
]
# Only the tokens a role resolves to. Vendoring the whole 26-token palette would
# invite a role to be added here rather than in the table that documents it.
TOKENS = ["mauve", "green", "peach", "red", "overlay1", "sapphire", "teal", "subtext0"]

rev = subprocess.run(["git", "-C", NEB, "rev-parse", "--short", "HEAD"],
                     capture_output=True, text=True).stdout.strip() or "unknown"

out = [
    "// Code generated by script/gen-palette.sh. DO NOT EDIT.",
    "//",
    "// Source: nebelung palette/*.hex.json at rev %s." % rev,
    "// Regenerate with: script/gen-palette.sh ~/code/workshop/nebelung",
    "",
    "package snug",
    "",
    "// palette holds the hex value of every nebelung token a role resolves to,",
    "// for each of the four variants. Roles are named in theme.go; this file is",
    "// only ever the numbers.",
    "var palette = map[Variant]map[string]string{",
]
for const, fname, note in VARIANTS:
    p = os.path.join(NEB, "palette", fname + ".hex.json")
    d = json.load(open(p))
    out.append("\t%s: { // %s" % (const, note))
    for t in TOKENS:
        out.append('\t\t%-12s "#%s",' % ('"%s":' % t, d[t]))
    out.append("\t},")
out.append("}")
print("\n".join(out))
