"""Render snug's two generated palettes from nebelung's four variant hex files.

Two outputs, one run, from one TOKENS list — see gen-palette.sh:

    palette.go     the Go side's `palette` map, hex only
    share/ui.sh    the bash fallback's `UI__HEX` and `UI__X256` blocks

They are generated TOGETHER on purpose. The fallback carrying its own copy of
the hex is what the move into this repo was for: two files hand-maintained in
step is a drift bug waiting for the first person who edits one of them.
"""
import json, subprocess, sys, os

MODE = sys.argv[1]          # "go" | "sh"
NEB = sys.argv[2]
VARIANTS = [
    ("Nebelung",            "nebelung",                     "dark  · the default"),
    ("NebelungHighContrast","nebelung-high-contrast",        "dark  · 19.9:1 text on base"),
    ("NebelungLatte",       "nebelung-latte",                "light"),
    ("NebelungLatteHC",     "nebelung-latte-high-contrast",  "light · 9.9:1"),
]
# Only the tokens a role resolves to. Vendoring the whole 26-token palette would
# invite a role to be added here rather than in the table that documents it.
TOKENS = ["mauve", "green", "peach", "red", "overlay1", "sapphire", "teal", "subtext0"]

# xterm's 6×6×6 cube samples each channel at these six values. They are NOT
# evenly spaced, which is why the nearest cube colour is searched for rather
# than divided out.
CUBE = [0, 95, 135, 175, 215, 255]


def dist(r1, g1, b1, r2, g2, b2):
    """theme.go's `dist`, digit for digit.

    Channels weighted the way the eye reads them — green hardest, blue least.
    Plain Euclidean RGB picks visibly wrong neighbours for the muted, low-chroma
    colours this palette is made of, and the fallback answering a DIFFERENT
    index from the binary is the one failure this whole arrangement exists to
    make impossible.
    """
    dr, dg, db = r1 - r2, g1 - g2, b1 - b2
    return 3 * dr * dr + 6 * dg * dg + db * db


def nearest256(hexv):
    """theme.go's `nearest256`: the closest of the 216 cube colours AND the 24 greys.

    Both are searched, because the grey ramp is much finer than the cube's grey
    diagonal — `overlay1` (#858585) lands within ΔE 2 of grey 245 and nowhere
    near any cube entry.
    """
    r, g, b = int(hexv[0:2], 16), int(hexv[2:4], 16), int(hexv[4:6], 16)
    best, bd = 0, 1 << 30
    for ri, rv in enumerate(CUBE):
        for gi, gv in enumerate(CUBE):
            for bi, bv in enumerate(CUBE):
                d = dist(r, g, b, rv, gv, bv)
                if d < bd:
                    best, bd = 16 + 36 * ri + 6 * gi + bi, d
    for i in range(24):
        v = 8 + i * 10
        d = dist(r, g, b, v, v, v)
        if d < bd:
            best, bd = 232 + i, d
    return best


def load(fname):
    with open(os.path.join(NEB, "palette", fname + ".hex.json")) as f:
        return json.load(f)


rev = subprocess.run(["git", "-C", NEB, "rev-parse", "--short", "HEAD"],
                     capture_output=True, text=True).stdout.strip() or "unknown"


def render_go():
    out = [
        "// Code generated by script/gen-palette.sh. DO NOT EDIT.",
        "//",
        "// Source: nebelung palette/*.hex.json at rev %s." % rev,
        "// Regenerate with: script/gen-palette.sh ~/code/workshop/nebelung",
        "",
        "package snug",
        "",
        "// palette holds the hex value of every nebelung token a role resolves to,",
        "// for each of the four variants. Roles are named in theme.go; this file is",
        "// only ever the numbers.",
        "var palette = map[Variant]map[string]string{",
    ]
    for const, fname, note in VARIANTS:
        d = load(fname)
        out.append("\t%s: { // %s" % (const, note))
        for t in TOKENS:
            out.append('\t\t%-12s "#%s",' % ('"%s":' % t, d[t]))
        out.append("\t},")
    out.append("}")
    return "\n".join(out)


def render_block(name, value):
    """One `declare -gA` block: four variant paragraphs, two entries a line.

    Two per line and aligned because the array is READ by a person checking one
    number against a terminal, not only by bash — thirty-two lines of one entry
    each is the same data nobody can scan.
    """
    lines = ["declare -gA %s=(" % name]
    for i, (_, fname, _) in enumerate(VARIANTS):
        d = load(fname)
        entries = ["[%s:%s]=%s" % (fname, t, value(d, t)) for t in TOKENS]
        # The right-hand column starts two cells past the widest left-hand entry
        # in THIS paragraph, so a variant's own names line up without the long
        # `nebelung-latte-high-contrast` block pushing the short ones sideways.
        col = max(len(e) for e in entries[0::2]) + 2
        if i:
            lines.append("")
        for a, b in zip(entries[0::2], entries[1::2]):
            lines.append("  %-*s%s" % (col, a, b))
    lines.append(")")
    return "\n".join(lines)


def render_sh():
    return "\n".join([
        render_block("UI__HEX", lambda d, t: d[t]),
        render_block("UI__X256", lambda d, t: nearest256(d[t])),
    ])


print(render_go() if MODE == "go" else render_sh())
