#!/usr/bin/env bash
# Regenerate BOTH palettes from a nebelung checkout.
#
#   script/gen-palette.sh ~/code/workshop/nebelung
#
#   palette.go     rewritten whole — it is nothing but the generated map
#   share/ui.sh    the two `declare -gA` blocks between the ▼▼▼/▲▲▲ markers,
#                  spliced in place; the rest of that file is hand-written
#
# snug cannot take nebelung as a dependency — nebelung is a Whiskers/Tera
# generator with no Go surface — so the hex values are VENDORED, and this script
# is the only thing allowed to write them. Hand-editing either table puts the
# family's CLIs back where they were: seven hand-picked 256-colour indices, ΔE
# 2–27 from the flavour every other tool on the machine is wearing.
#
# One script for both on purpose. The Go side and the bash fallback drawing
# DIFFERENT colours would be worse than having no fallback — it makes "which
# machine is this?" a question you have to ask about your own output — and two
# generators kept in step by hand is that bug with extra steps.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
neb="${1:-$HOME/code/workshop/nebelung}"
[ -d "$neb/palette" ] || { echo "no nebelung palette at $neb/palette" >&2; exit 1; }

# gofmt after, not clever alignment before: gofmt owns how a Go map literal is
# spaced, and CI fails on `gofmt -l`. A generator that guesses the padding is a
# generator whose next token name silently breaks the build.
python3 script/gen-palette.py go "$neb" > palette.go
gofmt -w palette.go

# Splice, rather than rewrite: ui.sh is 700 lines of hand-written painter with
# 40 lines of table in the middle. Written to a temp and moved into place so a
# failed generation cannot leave a half-written library on disk — this file is
# sourced by every family CLI on a machine without the binary.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
python3 script/gen-palette.py sh "$neb" > "$tmp"
python3 - "$tmp" <<'PY'
import sys
top = "# ▼▼▼ generated by script/gen-palette.sh — DO NOT EDIT ▼▼▼\n"
bot = "# ▲▲▲ end generated ▲▲▲\n"
src = open("share/ui.sh").read()
a, b = src.index(top) + len(top), src.index(bot)
open("share/ui.sh", "w").write(src[:a] + open(sys.argv[1]).read() + src[b:])
PY
